# scripts/evaluate.py

import os
import csv
import re
import time
from openai import OpenAI
from pathlib import Path
from tqdm import tqdm

MODEL_NAME = "gpt-4o-mini"
client = OpenAI(
    api_key=os.getenv("OPENAI_API_KEY")
)

EVALUATION_PROMPT = """###Task Description:
An user question instruction, a reference answer that gets a score of 5, and a response generated by a model to evaluate.
Your task is to provide a 'total rating' scoring how well the response answers the user question instruction compared to the reference answer.
If the response includes additional relevant factual information beyond the reference answer, that should not be penalized—as long as all points in the reference answer are correctly present.
Write a detailed feedback that assess the quality of the response strictly based on the given score rubric.
After writing a feedback, write a score that is an integer between 1 and 5. You should refer to the score rubric.
The output format should look as follows: "Feedback: {{write a feedback for criteria}} [RESULT] {{an integer number between 1 and 5}}"
Please do not generate any other opening, closing, and explanations. Be sure to include [RESULT] in your output.

###The instruction to evaluate:
{instruction}

###Response to evaluate:
{response}

###Reference Answer (Score 5):
{reference_answer}

###Score Rubrics:
[Is the response correct, accurate, and factual based on the reference answer?]
Score 1: The response is completely incorrect, inaccurate, and/or not factual.
Score 2: The response is mostly incorrect, inaccurate, and/or not factual.
Score 3: The response is somewhat correct, accurate, and/or factual.
Score 4: The response is mostly correct, accurate, and factual.
Score 5: The response is completely correct, accurate, and factual.
        (may include additional relevant facts beyond the reference answer.)

###Feedback:"""

def parse_feedback(raw: str) -> tuple[str, int]:
    """
    Extracts the Feedback text and the integer score from the model's reply.
    Expects format: "Feedback: ... [RESULT] X"
    
    Args:
        raw (str): Raw response text from the evaluation model
        
    Returns:
        tuple[str, int]: A tuple containing (feedback_text, score)
            - feedback_text: The extracted feedback text
            - score: The integer score (1-5), or 0 if parsing fails
    """
    m = re.search(r"Feedback:(.*)\[RESULT\]\s*(\d+)", raw, re.S)
    if not m:
        # fallback: return the raw reply and a sentinel score
        return raw.strip(), 0
    feedback = m.group(1).strip()
    score = int(m.group(2))
    return feedback, score

def main(
    infile: Path = Path("data/eval/output.csv"),
    outfile: Path = Path("data/eval/eval_results.csv"),
    delay: float = 0.5,
):
    """
    Evaluate model responses using OpenAI GPT-4o-mini as an evaluator.
    
    Reads a CSV file containing instruction-response pairs and reference answers,
    then uses OpenAI to score each response on a 1-5 scale with detailed feedback.
    
    Args:
        infile (Path): Input CSV file path containing instruction, response, and reference_answer columns
        outfile (Path): Output CSV file path for evaluation results
        delay (float): Delay in seconds between API calls to respect rate limits
    """

    # Prepare input/output
    with infile.open(newline="", encoding="utf-8") as f_in, \
         outfile.open("w", newline="", encoding="utf-8") as f_out:

        reader = csv.DictReader(f_in)
        fieldnames = reader.fieldnames + ["feedback", "score"]
        writer = csv.DictWriter(f_out, fieldnames=fieldnames)
        writer.writeheader()

        for row in tqdm(reader, desc="Evaluating with OpenAI"):
            prompt = EVALUATION_PROMPT.format(
                instruction=row["instruction"],
                response=row["response"],
                reference_answer=row["reference_answer"],
            )

            # Call OpenAI ChatCompletion
            response = client.chat.completions.create(
                model=MODEL_NAME, 
                messages=[
                    {"role": "system", "content": "You are a fair evaluator language model that evaluates the quality of a response to a user question instruction compared to a reference answer."},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.7,
            )
            text = response.choices[0].message.content

            feedback, score = parse_feedback(text)
            row.update({"feedback": feedback, "score": score})
            writer.writerow(row)

            # throttle to respect rate limits
            time.sleep(delay)

    print(f"✅ Evaluation complete — results in {outfile}")

if __name__ == "__main__":
    main()
